spring:
    application:
      name: EUREKA_SERVER
    security:
      basic:
        enabled: true
      user:
        name: eureka-user
        password: eureka-user

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false