spring:
  application:
    name: ms-cliente

server:
  port: 0 #Gera randomicamente uma porta aleatória.

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }